name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend (Maven)
        run: mvn clean package -DskipTests

      - name: Add SSH key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ssh_key

      - name: Add server to known_hosts
        run: ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Remove previous JAR from server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -f /home/atsao/deployed-files/statsranks.jar

      - name: Copy JAR to server
        run: |
          scp -i ssh_key -P ${{ secrets.SERVER_PORT }} target/statsranks.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/atsao/deployed-files/statsranks.jar

      - name: Restart backend service
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo systemctl stop statsranks.service
            sudo systemctl daemon-reload
            sudo systemctl restart statsranks.service